# Generated by Django 3.2.7 on 2021-09-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundSensor',
            fields=[
                ('device', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('soil_humidity', models.IntegerField()),
                ('air_humidity', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('battery_life', models.IntegerField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
