name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: docker build
      run: docker build . --file Dockerfile --tag soil-sensor-api:$(date +%s)
    - name: docker push
      run: docker push soil-sensor-api:$(date +%s)
